completed copy function
samandar-boymurodov/editorjs-codeflask pull request #2
Opened 2023-06-17 12:53 UTC by musojon1

2023-06-18 20:54 UTC, samandar-boymurodov requested changes

2023-06-18 20:54 UTC, samandar-boymurodov commented on src/codeflask.css
> +	padding: 5px;
padding: 5px 10px

2023-06-18 20:54 UTC, samandar-boymurodov commented on src/codeflask.js
> +        '<svg fill="#000000" height="1em" width="1em" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 512.42 512.42" xml:space="p
Can we keep svg strings in vars.js

2023-06-18 21:16 UTC, samandar-boymurodov commented
Let's increment the patch version by one. So that we can deploy with a new version.

2023-06-19 02:56 UTC, musojon1 commented on src/codeflask.js
> +        '<svg fill="#000000" height="1em" width="1em" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 512.42 512.42" xml:space="p
Yes,we can. I'll do it

2023-06-19 20:25 UTC, samandar-boymurodov approved these changes

2023-06-19 20:25 UTC, merged